using UnityEngine;
using SocketIOClient;
using System.Threading.Tasks;
using System;

public class SocketManager : MonoBehaviour
{
    private SocketIO client;
    public CubeLoader cubeLoader;

    void Awake()
    {
        cubeLoader = GetComponent<CubeLoader>();
    }

    async void Start()
    {
        client = new SocketIO(Var.BaseUrl);

        client.OnConnected += async (sender, e) =>
        {
            Debug.Log("ğŸŸ¢ Socket.IO ì—°ê²°");
        };

        client.On("cube_updated", response =>
        {
            Debug.Log("ğŸ’© Raw JSON: " + response.ToString());

            try
            {
                string jsonString = response.ToString();

                if (jsonString.TrimStart().StartsWith("[") && jsonString.TrimEnd().EndsWith("]"))
                {
                    jsonString = jsonString.TrimStart('[').TrimEnd(']');
                }

                CubeData cube = JsonUtility.FromJson<CubeData>(jsonString);
                HandleUpdatedCube(cube);
            }
            catch (Exception ex)
            {
                Debug.LogError("JSON íŒŒì‹± ì‹¤íŒ¨: " + ex.Message);
            }
        });

        await client.ConnectAsync();
    }

    async void OnDestroy()
    {
        await client.DisconnectAsync();
    }

    void HandleUpdatedCube(CubeData updatedCube)
    {
        Debug.Log($"ìˆ˜ì • id: {updatedCube.object_id}, now_status: {updatedCube.now_status}, remark: {updatedCube.remark}");

        if (cubeLoader.cubeSeqToIndexMap.TryGetValue(updatedCube.object_id, out int index))
        {
            // ë°ì´í„° ê°±ì‹ 
            cubeLoader.cubes[index] = updatedCube;

            // ìƒ‰ìƒ ì—…ë°ì´íŠ¸
            cubeLoader.UpdateCubeColor(updatedCube.object_id, updatedCube.now_status);

            Debug.Log($"Cube {updatedCube.object_id} ìƒ‰ìƒ ê°±ì‹  ì™„ë£Œ");
        }
        else
        {
            Debug.LogWarning($"Cube {updatedCube.object_id} ì—†ìŒ");
        }
    }
}
